### ISSUE TITLE
Custom focus state 

### ISSUE THREAD

**Issue by Stefan-Espant** [OvenMagnetron/fix-the-flow-wireflow#11]
Kijk of je als enhancement een custom focus state kan toevoegen zodat het nog meer oba uitstraalt:

```css
element:focus-visible {
  outline: none;
}

element:focus {
  background-color: white;
  color: red;
  border: 2px solid red;
}
```
